version: "3.0"
services:
  traefik:
    command: --web --docker --docker.domain=docker.localhost
    networks:
      - webgateway
    container_name: traefik
    image: containous/traefik:latest
    labels:
      - "traefik.backend=traefik"
      - "traefik.enable=true"
      - "traefik.frontend.entryPoints=http,https"
      - "traefik.frontend.rule=Host:traefik.extendedmind.org"
      - "traefik.port=8080"
      - "traefik.weight=1"
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      - "/etc/traefik/acme.json:/etc/traefik/acme.json"
      - "/home/ttiurani/dotfiles/analysis/docker/traefik.toml:/etc/traefik/traefik.toml"
      - "/var/run/docker.sock:/var/run/docker.sock"
networks:
  webgateway:
    driver: bridge
